services:
  hono-explore:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/hono-explore/
    environment:
      - PORT=8000
      - NODE_ENV=LOCAL
    depends_on:
      - hono-db
    networks:
        - my_network
    profiles: [backend]

  hono-db:
    container_name: hono-db
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    networks:
        - my_network

networks:
  my_network:
